apiVersion: v1
kind: Service
metadata:
  name: {{ include "wuda.fullname" . }}-frontend
  labels:
    app: {{ include "wuda.fullname" . }}-frontend
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - name: http
      port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.port }}
      {{- if eq .Values.service.frontend.type "NodePort" }}
      nodePort: {{ .Values.service.frontend.nodePort }}
      {{- end }}
  selector:
    app: {{ include "wuda.fullname" . }}-frontend
