apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "wuda.fullname" . }}-secrets"
type: Opaque
stringData:
  jwt_key: "{{ .Values.secrets.backend.JWT_KEY }}"
  secret_key: "{{ .Values.secrets.frontend.SECRET_KEY }}"
